
name: flutter-desktop-panel

services:
  app:
    image: flutter-desk-panel-backend
    restart: unless-stopped
    environment:
      - LOCATION=${LOCATION}
      - KID=${KID}
      - PROJECT_ID=${PROJECT_ID}
    volumes:
      - ./secrets:/app/app/secrets
      - ./cache:/app/app/cache
    ports:
      - "5000:5000"

