
name: flutter-desktop-panel

services:
  app:
    image: flutter-desk-panel-backend
    restart: unless-stopped
    environment:
      - QWEATHER_LOCATION
      - QWEATHER_KID
      - QWEATHER_PROJECT_ID
      - TZ=Asia/Shanghai
    volumes:
      - ./secrets:/app/app/secrets
      - ./cache:/app/app/.cache
    ports:
      - "5000:5000"

