
from contextlib import asynccontextmanager
from io import BytesIO
import os
from pathlib import Path
from typing import Literal
from uuid import uuid4

from fastapi import FastAPI, File, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from PIL import Image
from pydantic import BaseModel, Field
import pillow_heif
import socketio

from weather_service import fetch_current_weather, fetch_minutely_precipitation, fetch_air_quality
from message_service import delete_all_messages, delete_message, init_message_db, insert_message, list_messages

sio = socketio.AsyncServer(async_mode="asgi", cors_allowed_origins="*")
APP_DIR = Path(__file__).resolve().parent
WEB_DIR = APP_DIR.parent / "web"
UPLOADS_DIR = APP_DIR / ".cache" / "uploads"
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "").rstrip("/")
LOCAL_BASE_URL = os.getenv("LOCAL_BASE_URL", "http://127.0.0.1:5000").rstrip("/")
HEIC_CONTENT_TYPES = {
    "image/heic",
    "image/heif",
    "image/heic-sequence",
    "image/heif-sequence",
}
HEIC_SUFFIXES = {".heic", ".heif"}

LOCATION = os.getenv("LOCATION", "0, 0")
KID = os.getenv("KID")
PROJECT_ID = os.getenv("PROJECT_ID")


@asynccontextmanager
async def lifespan(_: FastAPI):
    UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
    init_message_db()
    yield


app = FastAPI(lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)
app.mount("/uploads", StaticFiles(directory=str(UPLOADS_DIR)), name="uploads")
socket_app = socketio.ASGIApp(sio, other_asgi_app=app)


class MessageCreateRequest(BaseModel):
    type: Literal["text", "image", "notify"]
    content: str = Field(min_length=1)
    sub_content: str | None = None
    source_name: str | None = None


class MessageNotifyWebhookRequest(BaseModel):
    app_name: str = Field(min_length=1)
    body: str = Field(min_length=1)


def _normalize_uploaded_image(
    data: bytes,
    filename: str | None,
    content_type: str | None,
) -> tuple[bytes, str]:
    suffix = Path(filename or "").suffix.lower()
    normalized_content_type = (content_type or "").lower()

    if suffix not in HEIC_SUFFIXES and normalized_content_type not in HEIC_CONTENT_TYPES:
        return data, suffix or ".jpg"

    pillow_heif.register_heif_opener()

    with Image.open(BytesIO(data)) as image:
        image.load()

        output = BytesIO()
        if "A" in image.getbands():
            rgba_image = image.convert("RGBA")
            background = Image.new("RGBA", rgba_image.size, (255, 255, 255, 255))
            flattened = Image.alpha_composite(background, rgba_image).convert("RGB")
            flattened.save(output, format="JPEG", quality=92, optimize=True)
        else:
            image.convert("RGB").save(output, format="JPEG", quality=92, optimize=True)

    return output.getvalue(), ".jpg"


@app.post("/api/messages")
async def create_message(request: MessageCreateRequest):
    if request.type == "image" and request.sub_content:
        raise HTTPException(status_code=400, detail="Image message does not support sub_content")
    if request.type == "text" and request.sub_content:
        raise HTTPException(status_code=400, detail="Text message subtitle is generated by server time")
    if request.type == "notify" and not request.source_name:
        raise HTTPException(status_code=400, detail="Notify messages require source_name")

    saved = insert_message(
        message_type=request.type,
        content=request.content,
        sub_content=request.sub_content,
        source_name=request.source_name,
    )
    await sio.emit("messages_updated", {"message": saved})
    return {"message": saved}


@app.get("/api/messages")
def get_messages():
    return {"messages": list_messages()}


@app.post("/api/messages/upload-image")
async def upload_image_message(request: Request, file: UploadFile = File(...)):
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Only image files are allowed")

    data = await file.read()
    if not data:
        raise HTTPException(status_code=400, detail="Empty file")

    data, suffix = _normalize_uploaded_image(data, file.filename, file.content_type)
    filename = f"{uuid4().hex}{suffix}"
    file_path = UPLOADS_DIR / filename

    file_path.write_bytes(data)
    base_url = PUBLIC_BASE_URL or LOCAL_BASE_URL
    image_url = f"{base_url}/uploads/{filename}"
    saved = insert_message(message_type="image", content=image_url)
    await sio.emit("messages_updated", {"message": saved})

    return {"url": image_url, "message": saved}


@app.post("/api/messages/webhook/notify")
async def webhook_notify_message(request: MessageNotifyWebhookRequest):
    saved = insert_message(
        message_type="notify",
        content=request.body,
        source_name=request.app_name,
    )
    await sio.emit("messages_updated", {"message": saved})
    return {"message": saved}


@app.delete('/api/messages/{message_id}')
async def delete_single_message(message_id: int):
    message = delete_message(message_id)
    if not message:
        raise HTTPException(status_code=404, detail="Message not found")
    
    # Delete associated image file if applicable
    if message.get('type') == 'image':
        content = message.get('content', '')
        if '/uploads/' in content:
            filename = content.split('/uploads/')[-1]
            if filename:
                file_path = UPLOADS_DIR / filename
                try:
                    if file_path.exists():
                        file_path.unlink()
                except Exception:
                    pass
    
    await sio.emit('messages_updated', {'deleted_id': message_id})
    return {'message': message}


@app.post('/api/messages/clear')
async def clear_messages(request: Request):
    # delete db rows and uploaded files
    removed = delete_all_messages()
    deleted_files = []
    for msg in removed:
        if msg.get('type') == 'image':
            content = msg.get('content', '')
            # try to extract filename under /uploads/
            if '/uploads/' in content:
                filename = content.split('/uploads/')[-1]
                if filename:
                    file_path = UPLOADS_DIR / filename
                    try:
                        if file_path.exists():
                            file_path.unlink()
                            deleted_files.append(str(file_path))
                    except Exception:
                        pass

    await sio.emit('messages_updated', {'cleared': True})
    return {'deleted_files': deleted_files, 'deleted_count': len(removed)}


app.mount("/", StaticFiles(directory=str(WEB_DIR), html=True), name="web")

def build_weather_payload():
    weather_data = fetch_current_weather(location=LOCATION, kid=KID, project_id=PROJECT_ID)
    weather_data = weather_data.get("now", {})

    precipitation_data = fetch_minutely_precipitation(location=LOCATION, kid=KID, project_id=PROJECT_ID)
    airquality_data = fetch_air_quality(location=LOCATION, kid=KID, project_id=PROJECT_ID)
    
    return {
        "weather": weather_data.get("text", ""),
        "temperature": weather_data.get("temp", ""),
        "icon": weather_data.get("icon", ""),
        "rain_notification": precipitation_data.get("summary", ""),
        "aqi": airquality_data.get("aqi", ""),
        "aqi_category": airquality_data.get("category", ""),
    }


def build_event_payload():
    event_data = {
        "name": "风力发电场电气设计",
        "time": "18:00",
        "date": "2026-05-05",
        "location": "主楼B412"
    }
    return event_data


@sio.event
async def connect(sid, environ, auth):
    print(f"Socket.IO client connected: {sid}")


@sio.event
async def disconnect(sid):
    print(f"Socket.IO client disconnected: {sid}")


@sio.event
async def request_weather(sid, data=None):
    await sio.emit("weather_data", build_weather_payload(), to=sid)


@sio.event
async def request_event(sid, data=None):
    await sio.emit("event_data", build_event_payload(), to=sid)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(socket_app, host="0.0.0.0", port=5000)
